name: dqr_chatbot
channels:
  - conda-forge
dependencies:
  - docutils==0.21.2
  - docx2txt==0.8
  - email_validator==2.2.0
  - faiss-cpu==1.9.0
  - langchain==0.3.4
  - langchain-huggingface==0.1.0
  - langchain-openai==0.2.3
  - langgraph==0.2.43
  - nltk==3.9.1
  - openai==1.52.0
  - PyMySQL==1.1.1
  - PyPDF2==3.0.1
  - pytorch==2.5.1
  - textblob==0.18.0.post0
  - wikipedia==1.4.0
  - youtube-transcript-api==0.6.2
  - streamlit
  - pip
  - pip:
      - tavily-python==0.5.0
      - pymupdf==1.24.12
      - ollama==0.3.3
      - langchain-ollama==0.2.0
      - huggingface-hub==0.25.1
      - duckduckgo_search==6.3.3
      - dotenv
      - langchain-community
      - plotly
      - tabulate