file_types = {
    'HEDIS Measures': '',
    'Medical Claims': 'medicalClaims',
    'Members': 'patient',
    'National Benchmarks': '',
    'Non Claims Expenses': 'NonClaimsExpense',
    'Operational Membership': 'OperationalMembership',
    'PCP Attribution': 'CorrectedPCPAttribution',
    'PFP': 'pfp',
    'Pharmacy Claims': 'pharmacyClaims',
    'PPR': 'ppr',
    'Provider': 'provider',
    'Provider Contract History': 'providerContractHistory',
    'Provider Service Location': 'organization',
    'Quality Gaps Pro': 'qualityGapsProspective',
    'Quality Gaps Retro': 'qualityGapsRetrospective',
    'Rate Code': 'rateCode',
    'Revenue': 'revenue',
    'Risk Gaps': 'riskGaps',
    'SDOH': 'sdoh',
    'State Benchmarks': '',
    'UAC File': 'uac',
    # 'VBP Roster': '',
}